/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Conexion.Conexion_db;
import Vista.TextPromt.TextPrompt;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *lll
 * @author sotog
 */
public class VistaPedidoRestaurante extends javax.swing.JFrame {

    DefaultTableModel modelo = new DefaultTableModel();

    /**
     * Creates new form VistaMercado
     */
    public VistaPedidoRestaurante() {
        initComponents();
        TextPrompt pHUsuario = new TextPrompt("Ingrese el id del almuerzo: ", txtId);
        TextPrompt pHUsuarioss = new TextPrompt("Ingrese la entrada del almuerzo : ", txtEntradaAlmuerzo);
        TextPrompt pHUsuariosss = new TextPrompt("Ingrese el centro del almuerzo: ", txtCentroAlmuerzo);
        TextPrompt pHUsuariossss = new TextPrompt("Ingrese el precio de este almuerzo: ", txtPrecio);
        TextPrompt pHUsuariosssss = new TextPrompt("Ingrese el nombre del almuerzo: ", txtNombre);
        TextPrompt pHUsuariossssss = new TextPrompt("Ingrese el postre para el almuerzo: ", txtPostre);
        TextPrompt pHUsuariosssssss = new TextPrompt("Ingrese el tipo de jugo: ", txtTipoJugo);
        setLocationRelativeTo(this);
        try {
            //crea un modelo de tabla

            //Establece el modelo recien creado a la tabla de usuarios
            almuerzo.setModel(modelo);
            // declara lass variables para preparar y ejecutar la consulta sql
            PreparedStatement ps = null;
            ResultSet rs = null;
            //Crea un objeto de conexion a la base de datos usando la clase previamente definida; Conexion_db
            Conexion_db conn = new Conexion_db();
            //Obtiene una conexion activa  a la base de datos
            Connection con = conn.getConexion();

            //Define la consulta SQL a ser ejecutada
            String sql = "SELECT * FROM almuerzo";
            //Prepara la consulta SQL para su ejecucion, esto ayuda a prevenir la inyeccion SQL
            ps = con.prepareStatement(sql);
            //Ejecuta la consulta y guarda el resultadoen las variables rs
            rs = ps.executeQuery();
            //Obtiene metadatos del resultado, como numero de columnas, nombre de columnas, etc
            ResultSetMetaData rsMd = (ResultSetMetaData) rs.getMetaData();
            //Obtiene la cantidad de colomunas del resultado
            int cantidadColumnas = rsMd.getColumnCount();
            //Define las columnas
            modelo.addColumn("Id");
            modelo.addColumn("Nombre");
            modelo.addColumn("precio");
            modelo.addColumn("EntradaAlmuerzo");
            modelo.addColumn("CentroAlmuerzo");
            modelo.addColumn("tipoPostre");
            modelo.addColumn("tipoJugo");

            int[] anchos = {120, 300, 300, 300, 300, 400, 300};
            for (int i = 0; i < almuerzo.getColumnCount(); i++) {
                //Establece el ancho preferido para cada columna
                almuerzo.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);

            }

            //mientras haya registros en el resultado
            while (rs.next()) {
                //crea un array para guardar los valores de las colmunas de un registro
                Object[] filas = new Object[cantidadColumnas];
                for (int i = 0; i < cantidadColumnas; i++) {
                    //Obtiene el objeto de la columna i+1(los indices en rs empiezan en 1, no en 0) y lo guarda 
                    filas[i] = rs.getObject(i + 1);

                }
                modelo.addRow(filas);

            }
            //Si ocurre algun errorSQL durante la ejecucion del bloque try, entra en este bloque catch

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        almuerzo = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnInsertar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        txtId = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        txtNombre = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        txtPrecio = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JSeparator();
        txtEntradaAlmuerzo = new javax.swing.JTextField();
        txtCentroAlmuerzo = new javax.swing.JTextField();
        txtPostre = new javax.swing.JTextField();
        txtTipoJugo = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(4, 13, 18));

        jPanel2.setBackground(new java.awt.Color(24, 61, 61));

        almuerzo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        almuerzo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                almuerzoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(almuerzo);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(147, 177, 166));
        jLabel1.setText("Ingresa la informacion del almuerzo:");

        btnInsertar.setBackground(new java.awt.Color(24, 61, 61));
        btnInsertar.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        btnInsertar.setForeground(new java.awt.Color(147, 177, 166));
        btnInsertar.setText("Insertar");
        btnInsertar.setActionCommand("Inicio");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(147, 177, 166));

        txtId.setBackground(new java.awt.Color(4, 13, 18));
        txtId.setForeground(new java.awt.Color(255, 255, 255));
        txtId.setBorder(null);

        jSeparator3.setBackground(new java.awt.Color(147, 177, 166));

        txtNombre.setBackground(new java.awt.Color(4, 13, 18));
        txtNombre.setForeground(new java.awt.Color(255, 255, 255));
        txtNombre.setBorder(null);

        jSeparator4.setBackground(new java.awt.Color(147, 177, 166));

        jSeparator5.setBackground(new java.awt.Color(147, 177, 166));

        txtPrecio.setBackground(new java.awt.Color(4, 13, 18));
        txtPrecio.setForeground(new java.awt.Color(255, 255, 255));
        txtPrecio.setBorder(null);

        jSeparator6.setBackground(new java.awt.Color(147, 177, 166));

        jSeparator7.setBackground(new java.awt.Color(147, 177, 166));

        btnModificar.setBackground(new java.awt.Color(24, 61, 61));
        btnModificar.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(147, 177, 166));
        btnModificar.setText("Modificar");
        btnModificar.setActionCommand("Inicio");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(24, 61, 61));
        btnEliminar.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(147, 177, 166));
        btnEliminar.setText("Eliminar");
        btnEliminar.setActionCommand("Inicio");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnBuscar.setBackground(new java.awt.Color(24, 61, 61));
        btnBuscar.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(147, 177, 166));
        btnBuscar.setText("Q");
        btnBuscar.setActionCommand("Inicio");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jSeparator8.setBackground(new java.awt.Color(147, 177, 166));

        txtEntradaAlmuerzo.setBackground(new java.awt.Color(4, 13, 18));
        txtEntradaAlmuerzo.setForeground(new java.awt.Color(255, 255, 255));
        txtEntradaAlmuerzo.setBorder(null);

        txtCentroAlmuerzo.setBackground(new java.awt.Color(4, 13, 18));
        txtCentroAlmuerzo.setForeground(new java.awt.Color(255, 255, 255));
        txtCentroAlmuerzo.setBorder(null);

        txtPostre.setBackground(new java.awt.Color(4, 13, 18));
        txtPostre.setForeground(new java.awt.Color(255, 255, 255));
        txtPostre.setBorder(null);

        txtTipoJugo.setBackground(new java.awt.Color(4, 13, 18));
        txtTipoJugo.setForeground(new java.awt.Color(255, 255, 255));
        txtTipoJugo.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jSeparator2)
                                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jSeparator6)
                                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtTipoJugo, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtEntradaAlmuerzo, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jSeparator4)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCentroAlmuerzo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPostre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnModificar)
                                .addGap(54, 54, 54))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnInsertar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(btnEliminar)
                        .addGap(72, 72, 72)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(txtEntradaAlmuerzo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtCentroAlmuerzo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPostre, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addComponent(txtTipoJugo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsertar)
                    .addComponent(btnModificar)
                    .addComponent(btnEliminar))
                .addGap(45, 45, 45))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jMenu1.setText("Más");

        jMenuItem1.setText("Volver");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        // TODO add your handling code here:
        PreparedStatement ps = null;
       
            try {

                Conexion_db obConexion_db = new Conexion_db();
                Connection conn = obConexion_db.getConexion();
                ps = conn.prepareStatement("INSERT INTO almuerzo (Id,Nombre,Precio,EntradaAlmuerzo,CentroAlmuerzo,tipoPostre,TipoJugo) VALUES (?,?,?,?,?,?,?)");
                ps.setString(1, txtId.getText());
                ps.setString(2, txtNombre.getText());
                ps.setString(3, txtPrecio.getText());
                ps.setString(4, txtEntradaAlmuerzo.getText());
                ps.setString(5, txtCentroAlmuerzo.getText());
                ps.setString(6, txtPostre.getText());
                ps.setString(7, txtTipoJugo.getText());

                ps.execute();

                JOptionPane.showMessageDialog(null, "Almuerzo guardado");

                Object[] fila = new Object[7];
                fila[0] = txtId.getText();
                fila[1] = txtNombre.getText();
                fila[2] = txtPrecio.getText();
                fila[3] = txtEntradaAlmuerzo.getText();
                fila[4] = txtCentroAlmuerzo.getText();
                fila[5] = txtPostre.getText();
                fila[6] = txtTipoJugo.getText();
                modelo.addRow(fila);

                limpiarCampos();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error al guardar");
            }
        
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        int fila = almuerzo.getSelectedRow();
        PreparedStatement ps = null;

        try {

            Conexion_db obConexion_db = new Conexion_db();
            Connection conn = obConexion_db.getConexion();
            ps = conn.prepareStatement("UPDATE  almuerzo SET nombre=?,precio=?,entradaAlmuerzo=?,centroAlmuerzo=?,tipoPostre=?,tipoJugo=? WHERE Id=?");

            ps.setString(1, txtNombre.getText());
            ps.setString(2, txtPrecio.getText());
            ps.setString(3, txtEntradaAlmuerzo.getText());
            ps.setString(4, txtCentroAlmuerzo.getText());
            ps.setString(5, txtPostre.getText());
            ps.setString(6, txtTipoJugo.getText());
            ps.setString(7, txtId.getText());

            ps.execute();

            JOptionPane.showMessageDialog(null, "Almuerzo modificado");
            almuerzo.setValueAt(txtId.getText(), fila, 0);
            almuerzo.setValueAt(txtNombre.getText(), fila, 1);
            almuerzo.setValueAt(txtPrecio.getText(), fila, 2);
            almuerzo.setValueAt(txtEntradaAlmuerzo.getText(), fila, 3);
            almuerzo.setValueAt(txtCentroAlmuerzo.getText(), fila, 4);
            almuerzo.setValueAt(txtPostre.getText(), fila, 5);
            almuerzo.setValueAt(txtTipoJugo.getText(), fila, 6);
            limpiarCampos();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al modificar");

        }


    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        PreparedStatement ps = null;
        if (txtId.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "LLene los campos");

        } else {
            try {

                Conexion_db objCon = new Conexion_db();
                Connection conn = objCon.getConexion();

                int fila = almuerzo.getSelectedRow();
                String codigo = almuerzo.getValueAt(fila, 0).toString();

                ps = conn.prepareStatement("DELETE FROM almuerzo WHERE Id=?");
                ps.setString(1, codigo);
                ps.execute();

                modelo.removeRow(fila);
                JOptionPane.showMessageDialog(null, "Almuerzo Eliminado");
                limpiarCampos();

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error al Eliminar el Almuerzo");
                System.out.println(ex.toString());
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String campo = txtId.getText();
        String where = "";
        if (!"".equals(campo)) {
            where = " WHERE Id = '" + campo + "'";
        }
        if (txtId.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "LLene los campos");

        } else {

            try {
                almuerzo.setModel(modelo);
                PreparedStatement ps = null;
                ResultSet rs = null;
                Conexion_db conn = new Conexion_db();
                Connection con = conn.getConexion();

                String sql = "SELECT * FROM almuerzo" + where;
                ps = con.prepareStatement(sql);//consulta de la base de datos
                rs = ps.executeQuery();// resultado de la consulta
                ResultSetMetaData rsMd = rs.getMetaData();
                int cantidadColumnas = rsMd.getColumnCount();

                modelo.addColumn("Id");
                modelo.addColumn("Nombre");
                modelo.addColumn("precio");
                modelo.addColumn("EntradaAlmuerzo");
                modelo.addColumn("CentroAlmuerzo");
                modelo.addColumn("tipoPostre");
                modelo.addColumn("tipoJugo");

                int[] anchos = {120, 170, 170, 170, 150, 170, 170};
                for (int i = 0; i < modelo.getColumnCount(); i++) {
                    almuerzo.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
                }

                while (rs.next()) {
                    Object[] filas = new Object[cantidadColumnas];
                    for (int i = 0; i < cantidadColumnas; i++) {
                        filas[i] = rs.getObject(i + 1);
                    }
                    modelo.addRow(filas);

                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new VistaInicio().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void almuerzoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_almuerzoMouseClicked
        // TODO add your handling code here:
        int fila = almuerzo.getSelectedRow();

        txtId.setText(almuerzo.getValueAt(fila, 0).toString());
        txtNombre.setText(almuerzo.getValueAt(fila, 1).toString());
        txtPrecio.setText(almuerzo.getValueAt(fila, 2).toString());
        txtEntradaAlmuerzo.setText(almuerzo.getValueAt(fila, 3).toString());
        txtCentroAlmuerzo.setText(almuerzo.getValueAt(fila, 4).toString());
        txtPostre.setText(almuerzo.getValueAt(fila, 5).toString());
        txtTipoJugo.setText(almuerzo.getValueAt(fila, 6).toString());

    }//GEN-LAST:event_almuerzoMouseClicked
    private void limpiarCampos() {
        txtCentroAlmuerzo.setText("");
        txtEntradaAlmuerzo.setText("");
        txtId.setText("");
        txtNombre.setText("");
        txtPrecio.setText("");
        txtPostre.setText("");
        txtTipoJugo.setText("");

    }

  

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPedidoRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPedidoRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPedidoRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPedidoRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPedidoRestaurante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable almuerzo;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextField txtCentroAlmuerzo;
    private javax.swing.JTextField txtEntradaAlmuerzo;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPostre;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtTipoJugo;
    // End of variables declaration//GEN-END:variables
}
